/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AaveV1CoreInterface,
  AaveV1CoreInterfaceInterface,
} from "../AaveV1CoreInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_reserve",
        type: "address",
      },
    ],
    name: "getReserveATokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AaveV1CoreInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AaveV1CoreInterfaceInterface {
    return new utils.Interface(_abi) as AaveV1CoreInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AaveV1CoreInterface {
    return new Contract(address, _abi, signerOrProvider) as AaveV1CoreInterface;
  }
}
