/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AaveV1ProviderInterface,
  AaveV1ProviderInterfaceInterface,
} from "../AaveV1ProviderInterface";

const _abi = [
  {
    inputs: [],
    name: "getLendingPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLendingPoolCore",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AaveV1ProviderInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AaveV1ProviderInterfaceInterface {
    return new utils.Interface(_abi) as AaveV1ProviderInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AaveV1ProviderInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AaveV1ProviderInterface;
  }
}
