/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AaveV2LendingPoolProviderInterface,
  AaveV2LendingPoolProviderInterfaceInterface,
} from "../AaveV2LendingPoolProviderInterface";

const _abi = [
  {
    inputs: [],
    name: "getLendingPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AaveV2LendingPoolProviderInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AaveV2LendingPoolProviderInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as AaveV2LendingPoolProviderInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AaveV2LendingPoolProviderInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AaveV2LendingPoolProviderInterface;
  }
}
