/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  DepositManagerProxyInterface,
  DepositManagerProxyInterfaceInterface,
} from "../DepositManagerProxyInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "depositERC20ForUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class DepositManagerProxyInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DepositManagerProxyInterfaceInterface {
    return new utils.Interface(_abi) as DepositManagerProxyInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DepositManagerProxyInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DepositManagerProxyInterface;
  }
}
