/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  QiTokenInterface,
  QiTokenInterfaceInterface,
} from "../QiTokenInterface";

const _abi = [
  {
    inputs: [],
    name: "isQiToken",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "underlying",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class QiTokenInterface__factory {
  static readonly abi = _abi;
  static createInterface(): QiTokenInterfaceInterface {
    return new utils.Interface(_abi) as QiTokenInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): QiTokenInterface {
    return new Contract(address, _abi, signerOrProvider) as QiTokenInterface;
  }
}
