/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TokenFaucetProxyFactoryInterface,
  TokenFaucetProxyFactoryInterfaceInterface,
} from "../TokenFaucetProxyFactoryInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "contract TokenFaucetInterface[]",
        name: "tokenFaucets",
        type: "address[]",
      },
    ],
    name: "claimAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenFaucetProxyFactoryInterface__factory {
  static readonly abi = _abi;
  static createInterface(): TokenFaucetProxyFactoryInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as TokenFaucetProxyFactoryInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenFaucetProxyFactoryInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TokenFaucetProxyFactoryInterface;
  }
}
