/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConnectV2BasicERC721Interface extends utils.Interface {
  functions: {
    "depositERC721(address,uint256,uint256,uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "withdrawERC721(address,uint256,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositERC721",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawERC721",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC721",
    data: BytesLike
  ): Result;

  events: {
    "LogDepositERC721(address,address,uint256,uint256,uint256)": EventFragment;
    "LogWithdrawERC721(address,uint256,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogDepositERC721"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogWithdrawERC721"): EventFragment;
}

export type LogDepositERC721Event = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    erc721: string;
    from: string;
    tokenId: BigNumber;
    getId: BigNumber;
    setId: BigNumber;
  }
>;

export type LogDepositERC721EventFilter =
  TypedEventFilter<LogDepositERC721Event>;

export type LogWithdrawERC721Event = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  {
    erc721: string;
    tokenId: BigNumber;
    to: string;
    getId: BigNumber;
    setId: BigNumber;
  }
>;

export type LogWithdrawERC721EventFilter =
  TypedEventFilter<LogWithdrawERC721Event>;

export interface ConnectV2BasicERC721 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectV2BasicERC721Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositERC721(
      token: string,
      tokenId: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    withdrawERC721(
      token: string,
      tokenId: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositERC721(
    token: string,
    tokenId: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  withdrawERC721(
    token: string,
    tokenId: BigNumberish,
    to: string,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositERC721(
      token: string,
      tokenId: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { _eventName: string; _eventParam: string }>;

    name(overrides?: CallOverrides): Promise<string>;

    withdrawERC721(
      token: string,
      tokenId: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { _eventName: string; _eventParam: string }>;
  };

  filters: {
    "LogDepositERC721(address,address,uint256,uint256,uint256)"(
      erc721?: string | null,
      from?: null,
      tokenId?: null,
      getId?: null,
      setId?: null
    ): LogDepositERC721EventFilter;
    LogDepositERC721(
      erc721?: string | null,
      from?: null,
      tokenId?: null,
      getId?: null,
      setId?: null
    ): LogDepositERC721EventFilter;

    "LogWithdrawERC721(address,uint256,address,uint256,uint256)"(
      erc721?: string | null,
      tokenId?: null,
      to?: string | null,
      getId?: null,
      setId?: null
    ): LogWithdrawERC721EventFilter;
    LogWithdrawERC721(
      erc721?: string | null,
      tokenId?: null,
      to?: string | null,
      getId?: null,
      setId?: null
    ): LogWithdrawERC721EventFilter;
  };

  estimateGas: {
    depositERC721(
      token: string,
      tokenId: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawERC721(
      token: string,
      tokenId: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositERC721(
      token: string,
      tokenId: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawERC721(
      token: string,
      tokenId: BigNumberish,
      to: string,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
