/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConnectV2InstaPoolInterface extends utils.Interface {
  functions: {
    "flashBorrowAndCast(address,uint256,uint256,bytes)": FunctionFragment;
    "flashPayback(address,uint256,uint256,uint256)": FunctionFragment;
    "instaPool()": FunctionFragment;
    "name()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "flashBorrowAndCast",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flashPayback",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "instaPool", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "flashBorrowAndCast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flashPayback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instaPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;

  events: {
    "LogFlashBorrow(address,uint256)": EventFragment;
    "LogFlashMultiBorrow(address[],uint256[])": EventFragment;
    "LogFlashMultiPayback(address[],uint256[])": EventFragment;
    "LogFlashPayback(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogFlashBorrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFlashMultiBorrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFlashMultiPayback"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFlashPayback"): EventFragment;
}

export type LogFlashBorrowEvent = TypedEvent<
  [string, BigNumber],
  { token: string; tokenAmt: BigNumber }
>;

export type LogFlashBorrowEventFilter = TypedEventFilter<LogFlashBorrowEvent>;

export type LogFlashMultiBorrowEvent = TypedEvent<
  [string[], BigNumber[]],
  { token: string[]; tokenAmts: BigNumber[] }
>;

export type LogFlashMultiBorrowEventFilter =
  TypedEventFilter<LogFlashMultiBorrowEvent>;

export type LogFlashMultiPaybackEvent = TypedEvent<
  [string[], BigNumber[]],
  { token: string[]; tokenAmts: BigNumber[] }
>;

export type LogFlashMultiPaybackEventFilter =
  TypedEventFilter<LogFlashMultiPaybackEvent>;

export type LogFlashPaybackEvent = TypedEvent<
  [string, BigNumber],
  { token: string; tokenAmt: BigNumber }
>;

export type LogFlashPaybackEventFilter = TypedEventFilter<LogFlashPaybackEvent>;

export interface ConnectV2InstaPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectV2InstaPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    flashBorrowAndCast(
      token: string,
      amt: BigNumberish,
      route: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    flashPayback(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    instaPool(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;
  };

  flashBorrowAndCast(
    token: string,
    amt: BigNumberish,
    route: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  flashPayback(
    token: string,
    amt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  instaPool(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    flashBorrowAndCast(
      token: string,
      amt: BigNumberish,
      route: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    flashPayback(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    instaPool(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "LogFlashBorrow(address,uint256)"(
      token?: null,
      tokenAmt?: null
    ): LogFlashBorrowEventFilter;
    LogFlashBorrow(token?: null, tokenAmt?: null): LogFlashBorrowEventFilter;

    "LogFlashMultiBorrow(address[],uint256[])"(
      token?: null,
      tokenAmts?: null
    ): LogFlashMultiBorrowEventFilter;
    LogFlashMultiBorrow(
      token?: null,
      tokenAmts?: null
    ): LogFlashMultiBorrowEventFilter;

    "LogFlashMultiPayback(address[],uint256[])"(
      token?: null,
      tokenAmts?: null
    ): LogFlashMultiPaybackEventFilter;
    LogFlashMultiPayback(
      token?: null,
      tokenAmts?: null
    ): LogFlashMultiPaybackEventFilter;

    "LogFlashPayback(address,uint256)"(
      token?: null,
      tokenAmt?: null
    ): LogFlashPaybackEventFilter;
    LogFlashPayback(token?: null, tokenAmt?: null): LogFlashPaybackEventFilter;
  };

  estimateGas: {
    flashBorrowAndCast(
      token: string,
      amt: BigNumberish,
      route: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    flashPayback(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    instaPool(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    flashBorrowAndCast(
      token: string,
      amt: BigNumberish,
      route: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    flashPayback(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    instaPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
