/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface EventHelpersInterface extends utils.Interface {
  functions: {
    "connectorID()": FunctionFragment;
    "deposit(address,uint256,uint256,uint256)": FunctionFragment;
    "withdraw(address,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "connectorID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "connectorID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "LogDepositLiquidity(address,uint256,uint256,uint256)": EventFragment;
    "LogFlashBorrow(address,uint256,uint256,uint256)": EventFragment;
    "LogFlashPayback(address,uint256,uint256,uint256,uint256)": EventFragment;
    "LogOriginFeeCollected(address,address,uint256,uint256)": EventFragment;
    "LogWithdrawLiquidity(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogDepositLiquidity"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFlashBorrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogFlashPayback"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogOriginFeeCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogWithdrawLiquidity"): EventFragment;
}

export type LogDepositLiquidityEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { token: string; tokenAmt: BigNumber; getId: BigNumber; setId: BigNumber }
>;

export type LogDepositLiquidityEventFilter =
  TypedEventFilter<LogDepositLiquidityEvent>;

export type LogFlashBorrowEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { token: string; tokenAmt: BigNumber; getId: BigNumber; setId: BigNumber }
>;

export type LogFlashBorrowEventFilter = TypedEventFilter<LogFlashBorrowEvent>;

export type LogFlashPaybackEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    token: string;
    tokenAmt: BigNumber;
    feeCollected: BigNumber;
    getId: BigNumber;
    setId: BigNumber;
  }
>;

export type LogFlashPaybackEventFilter = TypedEventFilter<LogFlashPaybackEvent>;

export type LogOriginFeeCollectedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    origin: string;
    token: string;
    tokenAmt: BigNumber;
    originFeeAmt: BigNumber;
  }
>;

export type LogOriginFeeCollectedEventFilter =
  TypedEventFilter<LogOriginFeeCollectedEvent>;

export type LogWithdrawLiquidityEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { token: string; tokenAmt: BigNumber; getId: BigNumber; setId: BigNumber }
>;

export type LogWithdrawLiquidityEventFilter =
  TypedEventFilter<LogWithdrawLiquidityEvent>;

export interface EventHelpers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventHelpersInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    deposit(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  connectorID(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

  deposit(
    token: string,
    amt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    token: string,
    amt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    connectorID(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _type: BigNumber; _id: BigNumber }>;

    deposit(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "LogDepositLiquidity(address,uint256,uint256,uint256)"(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogDepositLiquidityEventFilter;
    LogDepositLiquidity(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogDepositLiquidityEventFilter;

    "LogFlashBorrow(address,uint256,uint256,uint256)"(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogFlashBorrowEventFilter;
    LogFlashBorrow(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogFlashBorrowEventFilter;

    "LogFlashPayback(address,uint256,uint256,uint256,uint256)"(
      token?: string | null,
      tokenAmt?: null,
      feeCollected?: null,
      getId?: null,
      setId?: null
    ): LogFlashPaybackEventFilter;
    LogFlashPayback(
      token?: string | null,
      tokenAmt?: null,
      feeCollected?: null,
      getId?: null,
      setId?: null
    ): LogFlashPaybackEventFilter;

    "LogOriginFeeCollected(address,address,uint256,uint256)"(
      origin?: string | null,
      token?: string | null,
      tokenAmt?: null,
      originFeeAmt?: null
    ): LogOriginFeeCollectedEventFilter;
    LogOriginFeeCollected(
      origin?: string | null,
      token?: string | null,
      tokenAmt?: null,
      originFeeAmt?: null
    ): LogOriginFeeCollectedEventFilter;

    "LogWithdrawLiquidity(address,uint256,uint256,uint256)"(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogWithdrawLiquidityEventFilter;
    LogWithdrawLiquidity(
      token?: string | null,
      tokenAmt?: null,
      getId?: null,
      setId?: null
    ): LogWithdrawLiquidityEventFilter;
  };

  estimateGas: {
    connectorID(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    connectorID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      token: string,
      amt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
