/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface InstaOneMappingInterface extends utils.Interface {
  functions: {
    "changeOneProtoAddress(address)": FunctionFragment;
    "connectors()": FunctionFragment;
    "instaIndex()": FunctionFragment;
    "oneProtoAddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeOneProtoAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "connectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "instaIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oneProtoAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeOneProtoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "connectors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "instaIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oneProtoAddress",
    data: BytesLike
  ): Result;

  events: {
    "LogChangeOneProto(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogChangeOneProto"): EventFragment;
}

export type LogChangeOneProtoEvent = TypedEvent<[string], { oneProto: string }>;

export type LogChangeOneProtoEventFilter =
  TypedEventFilter<LogChangeOneProtoEvent>;

export interface InstaOneMapping extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InstaOneMappingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeOneProtoAddress(
      _oneProtoAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    connectors(overrides?: CallOverrides): Promise<[string]>;

    instaIndex(overrides?: CallOverrides): Promise<[string]>;

    oneProtoAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  changeOneProtoAddress(
    _oneProtoAddr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  connectors(overrides?: CallOverrides): Promise<string>;

  instaIndex(overrides?: CallOverrides): Promise<string>;

  oneProtoAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    changeOneProtoAddress(
      _oneProtoAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    connectors(overrides?: CallOverrides): Promise<string>;

    instaIndex(overrides?: CallOverrides): Promise<string>;

    oneProtoAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "LogChangeOneProto(address)"(oneProto?: null): LogChangeOneProtoEventFilter;
    LogChangeOneProto(oneProto?: null): LogChangeOneProtoEventFilter;
  };

  estimateGas: {
    changeOneProtoAddress(
      _oneProtoAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    connectors(overrides?: CallOverrides): Promise<BigNumber>;

    instaIndex(overrides?: CallOverrides): Promise<BigNumber>;

    oneProtoAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeOneProtoAddress(
      _oneProtoAddr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    connectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    instaIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oneProtoAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
