/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type IncentiveKeyStruct = {
  rewardToken: string;
  pool: string;
  startTime: BigNumberish;
  endTime: BigNumberish;
  refundee: string;
};

export type IncentiveKeyStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  rewardToken: string;
  pool: string;
  startTime: BigNumber;
  endTime: BigNumber;
  refundee: string;
};

export interface IUniswapV3StakerInterface extends utils.Interface {
  functions: {
    "claimReward(address,address,uint256)": FunctionFragment;
    "createIncentive((address,address,uint256,uint256,address),uint256)": FunctionFragment;
    "deposits(uint256)": FunctionFragment;
    "endIncentive((address,address,uint256,uint256,address))": FunctionFragment;
    "factory()": FunctionFragment;
    "getRewardInfo((address,address,uint256,uint256,address),uint256)": FunctionFragment;
    "incentives(bytes32)": FunctionFragment;
    "maxIncentiveDuration()": FunctionFragment;
    "maxIncentiveStartLeadTime()": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "nonfungiblePositionManager()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "rewards(address,address)": FunctionFragment;
    "stakeToken((address,address,uint256,uint256,address),uint256)": FunctionFragment;
    "stakes(uint256,bytes32)": FunctionFragment;
    "transferDeposit(uint256,address)": FunctionFragment;
    "unstakeToken((address,address,uint256,uint256,address),uint256)": FunctionFragment;
    "withdrawToken(uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIncentive",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endIncentive",
    values: [IncentiveKeyStruct]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRewardInfo",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incentives",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxIncentiveDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxIncentiveStartLeadTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "nonfungiblePositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeToken",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferDeposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeToken",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "incentives", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxIncentiveDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxIncentiveStartLeadTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nonfungiblePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;

  events: {
    "DepositTransferred(uint256,address,address)": EventFragment;
    "IncentiveCreated(address,address,uint256,uint256,address,uint256)": EventFragment;
    "IncentiveEnded(bytes32,uint256)": EventFragment;
    "RewardClaimed(address,uint256)": EventFragment;
    "TokenStaked(uint256,bytes32,uint128)": EventFragment;
    "TokenUnstaked(uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IncentiveCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IncentiveEnded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenStaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUnstaked"): EventFragment;
}

export type DepositTransferredEvent = TypedEvent<
  [BigNumber, string, string],
  { tokenId: BigNumber; oldOwner: string; newOwner: string }
>;

export type DepositTransferredEventFilter =
  TypedEventFilter<DepositTransferredEvent>;

export type IncentiveCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string, BigNumber],
  {
    rewardToken: string;
    pool: string;
    startTime: BigNumber;
    endTime: BigNumber;
    refundee: string;
    reward: BigNumber;
  }
>;

export type IncentiveCreatedEventFilter =
  TypedEventFilter<IncentiveCreatedEvent>;

export type IncentiveEndedEvent = TypedEvent<
  [string, BigNumber],
  { incentiveId: string; refund: BigNumber }
>;

export type IncentiveEndedEventFilter = TypedEventFilter<IncentiveEndedEvent>;

export type RewardClaimedEvent = TypedEvent<
  [string, BigNumber],
  { to: string; reward: BigNumber }
>;

export type RewardClaimedEventFilter = TypedEventFilter<RewardClaimedEvent>;

export type TokenStakedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { tokenId: BigNumber; incentiveId: string; liquidity: BigNumber }
>;

export type TokenStakedEventFilter = TypedEventFilter<TokenStakedEvent>;

export type TokenUnstakedEvent = TypedEvent<
  [BigNumber, string],
  { tokenId: BigNumber; incentiveId: string }
>;

export type TokenUnstakedEventFilter = TypedEventFilter<TokenUnstakedEvent>;

export interface IUniswapV3Staker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUniswapV3StakerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimReward(
      rewardToken: string,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposits(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, number] & {
        owner: string;
        numberOfStakes: number;
        tickLower: number;
        tickUpper: number;
      }
    >;

    endIncentive(
      key: IncentiveKeyStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    incentives(
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        totalRewardUnclaimed: BigNumber;
        totalSecondsClaimedX128: BigNumber;
        numberOfStakes: BigNumber;
      }
    >;

    maxIncentiveDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxIncentiveStartLeadTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    multicall(
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewards(
      rewardToken: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rewardsOwed: BigNumber }>;

    stakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakes(
      tokenId: BigNumberish,
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        secondsPerLiquidityInsideInitialX128: BigNumber;
        liquidity: BigNumber;
      }
    >;

    transferDeposit(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawToken(
      tokenId: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimReward(
    rewardToken: string,
    to: string,
    amountRequested: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createIncentive(
    key: IncentiveKeyStruct,
    reward: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposits(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, number] & {
      owner: string;
      numberOfStakes: number;
      tickLower: number;
      tickUpper: number;
    }
  >;

  endIncentive(
    key: IncentiveKeyStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getRewardInfo(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  incentives(
    incentiveId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      totalRewardUnclaimed: BigNumber;
      totalSecondsClaimedX128: BigNumber;
      numberOfStakes: BigNumber;
    }
  >;

  maxIncentiveDuration(overrides?: CallOverrides): Promise<BigNumber>;

  maxIncentiveStartLeadTime(overrides?: CallOverrides): Promise<BigNumber>;

  multicall(
    data: BytesLike[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    operator: string,
    from: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewards(
    rewardToken: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  stakeToken(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakes(
    tokenId: BigNumberish,
    incentiveId: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      secondsPerLiquidityInsideInitialX128: BigNumber;
      liquidity: BigNumber;
    }
  >;

  transferDeposit(
    tokenId: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstakeToken(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawToken(
    tokenId: BigNumberish,
    to: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimReward(
      rewardToken: string,
      to: string,
      amountRequested: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deposits(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, number] & {
        owner: string;
        numberOfStakes: number;
        tickLower: number;
        tickUpper: number;
      }
    >;

    endIncentive(
      key: IncentiveKeyStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;

    getRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        reward: BigNumber;
        secondsInsideX128: BigNumber;
      }
    >;

    incentives(
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        totalRewardUnclaimed: BigNumber;
        totalSecondsClaimedX128: BigNumber;
        numberOfStakes: BigNumber;
      }
    >;

    maxIncentiveDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maxIncentiveStartLeadTime(overrides?: CallOverrides): Promise<BigNumber>;

    multicall(data: BytesLike[], overrides?: CallOverrides): Promise<string[]>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    rewards(
      rewardToken: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakes(
      tokenId: BigNumberish,
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        secondsPerLiquidityInsideInitialX128: BigNumber;
        liquidity: BigNumber;
      }
    >;

    transferDeposit(
      tokenId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawToken(
      tokenId: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositTransferred(uint256,address,address)"(
      tokenId?: BigNumberish | null,
      oldOwner?: string | null,
      newOwner?: string | null
    ): DepositTransferredEventFilter;
    DepositTransferred(
      tokenId?: BigNumberish | null,
      oldOwner?: string | null,
      newOwner?: string | null
    ): DepositTransferredEventFilter;

    "IncentiveCreated(address,address,uint256,uint256,address,uint256)"(
      rewardToken?: string | null,
      pool?: string | null,
      startTime?: null,
      endTime?: null,
      refundee?: null,
      reward?: null
    ): IncentiveCreatedEventFilter;
    IncentiveCreated(
      rewardToken?: string | null,
      pool?: string | null,
      startTime?: null,
      endTime?: null,
      refundee?: null,
      reward?: null
    ): IncentiveCreatedEventFilter;

    "IncentiveEnded(bytes32,uint256)"(
      incentiveId?: BytesLike | null,
      refund?: null
    ): IncentiveEndedEventFilter;
    IncentiveEnded(
      incentiveId?: BytesLike | null,
      refund?: null
    ): IncentiveEndedEventFilter;

    "RewardClaimed(address,uint256)"(
      to?: string | null,
      reward?: null
    ): RewardClaimedEventFilter;
    RewardClaimed(to?: string | null, reward?: null): RewardClaimedEventFilter;

    "TokenStaked(uint256,bytes32,uint128)"(
      tokenId?: BigNumberish | null,
      incentiveId?: BytesLike | null,
      liquidity?: null
    ): TokenStakedEventFilter;
    TokenStaked(
      tokenId?: BigNumberish | null,
      incentiveId?: BytesLike | null,
      liquidity?: null
    ): TokenStakedEventFilter;

    "TokenUnstaked(uint256,bytes32)"(
      tokenId?: BigNumberish | null,
      incentiveId?: BytesLike | null
    ): TokenUnstakedEventFilter;
    TokenUnstaked(
      tokenId?: BigNumberish | null,
      incentiveId?: BytesLike | null
    ): TokenUnstakedEventFilter;
  };

  estimateGas: {
    claimReward(
      rewardToken: string,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposits(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    endIncentive(
      key: IncentiveKeyStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    incentives(
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxIncentiveDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maxIncentiveStartLeadTime(overrides?: CallOverrides): Promise<BigNumber>;

    multicall(
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewards(
      rewardToken: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakes(
      tokenId: BigNumberish,
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferDeposit(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawToken(
      tokenId: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimReward(
      rewardToken: string,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposits(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    endIncentive(
      key: IncentiveKeyStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    incentives(
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxIncentiveDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxIncentiveStartLeadTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multicall(
      data: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nonfungiblePositionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      operator: string,
      from: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewards(
      rewardToken: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakes(
      tokenId: BigNumberish,
      incentiveId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferDeposit(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawToken(
      tokenId: BigNumberish,
      to: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
