/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TroveManagerLikeInterface extends utils.Interface {
  functions: {
    "getTroveColl(address)": FunctionFragment;
    "getTroveDebt(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTroveColl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTroveDebt",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTroveColl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTroveDebt",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TroveManagerLike extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TroveManagerLikeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getTroveColl(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTroveDebt(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getTroveColl(
    _borrower: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTroveDebt(
    _borrower: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getTroveColl(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTroveDebt(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getTroveColl(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTroveDebt(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTroveColl(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTroveDebt(
      _borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
