export const connectMapping: Record<string, any> = {
  "1INCH-A": "ConnectV2OneInch",
  "1INCH-B": "ConnectV2OneProto",
  "AAVE-V1-A": "ConnectV2AaveV1",
  "AAVE-V2-A": "ConnectV2AaveV2",
  "AUTHORITY-A": "ConnectV2Auth",
  "BASIC-A": "ConnectV2Basic",
  "COMP-A": "ConnectV2COMP",
  "COMPOUND-A": "ConnectV2Compound",
  "DYDX-A": "ConnectV2Dydx",
  "FEE-A": "ConnectV2Fee",
  "GELATO-A": "ConnectV2Gelato",
  "MAKERDAO-A": "ConnectV2Maker",
  "UNISWAP-A": "ConnectV2UniswapV2",
};

export const connectors = [
  "1INCH-A",
  "1INCH-B",
  "AAVE-V1-A",
  "AAVE-V2-A",
  "AUTHORITY-A",
  "BASIC-A",
  "COMP-A",
  "COMPOUND-A",
  "DYDX-A",
  "FEE-A",
  "GELATO-A",
  "MAKERDAO-A",
  "UNISWAP-A",
];
